# This file contains mapping information for log levels of this component
apiVersion: v1
metavalues:
  mainLogLevel:
    name: Log-Level
    description: The central configuration value to set the log level for this component
    keys:
      - path: global.logLevel
        mapping:
          debug: 5
          info: 2
          warn: 1
          error: 0