global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
  logLevel: 5

manager:
  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      memory: 105M
# Image of the snapshot controller.
snapshot_controller_image: registry.k8s.io/sig-storage/snapshot-controller:v8.2.1