global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
# Image of the snapshot controller.
snapshot_controller_image: registry.k8s.io/sig-storage/snapshot-controller:v6.3.4

