global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
# Image of the snapshot controller. The 7.0.2 release still using 6.3.1 controller.
# See: https://github.com/kubernetes-csi/external-snapshotter/blob/v7.0.2/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
snapshot_controller_image: registry.k8s.io/sig-storage/snapshot-controller:v6.3.1

